apiVersion: v1
kind: PersistentVolume
metadata:
  name: planetservice-postgres-{{ .Release.Name }}-pv
  labels:
    app: {{ .Values.postgres.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.postgres.volumeCapacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.hostPath }}
