apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planetservice-postgres-{{ .Release.Name }}-pvc
  labels:
    app: {{ .Values.postgres.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.volumeCapacity }}
  volumeName: planetservice-postgres-{{ .Release.Name }}-pv
