apiVersion: v1
kind: Service
metadata:
  name: planetservice-postgres-{{ .Release.Name }}-svc
  labels:
    app: {{ .Values.postgres.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  selector:
    app: planetservice-postgres-{{ .Release.Name }}-container
  ports:
    - name: postgres-listener
      protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.containerPort }}
  type: {{ .Values.postgres.service.type }}
