apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb3RuZXRvZ2FtZS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiZG90bmV0b2dhbWUiLCJwYXNzd29yZCI6IlJ4cm8wL0RyTT1KUzM3MEV4Q2pVOElSPWdjQWZ1Nj10IiwiZW1haWwiOiJ0aW1vZmV5LmtydWtAZWZmZWN0aXZlLXNvZnQuY29tIiwiYXV0aCI6IlpHOTBibVYwYjJkaGJXVTZVbmh5YnpBdlJISk5QVXBUTXpjd1JYaERhbFU0U1ZJOVoyTkJablUyUFhRPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2022-07-06T09:34:44Z"
  name: ogame-container-registry-config-{{ .Release.Name }}
  resourceVersion: "36520"
  uid: a53f3fe8-6d55-4170-b29d-6307a2cdfa85
  labels:
    owner: {{ .Values.owner }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
