apiVersion: v1
kind: Secret
metadata:
  name: planetservice-{{ .Release.Name }}-secrets
  labels:
    app: {{ .Values.planetservice.labels.app }}
    secretEnv: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
stringData:
  postgresPassword: "123"
  postgresDatabase: "PlanetDb"
  databaseConnection: "Host=planetservice-postgres-{{ .Release.Name }}-svc;Port={{ .Values.postgres.servicePort }};Database=PlanetDb;User Id=postgres;Password=123"
