apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: planetservice-{{ .Release.Name }}-hpa
  labels:
    app: {{ .Values.planetservice.labels.app }}
    env: {{ .Values.env }}
    targetApp: {{ .Values.targetApp }}
    namespace: {{ .Values.namespace }}
    owner: {{ .Values.owner }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: planetservice-{{ .Release.Name }}-deploy
  minReplicas: {{ .Values.planetservice.autoscaling.replicas.min }}
  maxReplicas: {{ .Values.planetservice.autoscaling.replicas.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.planetservice.autoscaling.cpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.planetservice.autoscaling.memoryAverageUtilization }}
