env: dev
targetApp: planetservice
namespace: dev
owner: DenisMakarevich

postgres:
  labels:
    app: postgres

  volumeCapacity: 1Gi
  hostPath: /planetservice/dev/data/postgres-volume

  containerPort: 5432
  servicePort: 5432

  deployment:
    image: postgres:14.1
    resources:
      requests:
        memory: "256Mi"
        cpu: "300m"
      limits:
        memory: "512Mi"
        cpu: "1"

  service:
    type: ClusterIP

planetservice:
  containerPort: 80
  servicePort: 5064

  labels:
    app: planetservice

  deployment:
    image: "dotnetogame.azurecr.io/planet-service:dev-latest"
    init:
      image: "dotnetogame.azurecr.io/planet-migrator:dev-latest"
    imagePullPolicy: Always
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "1"
    probe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1

  autoscaling:
    replicas:
      min: 2
      max: 2
    cpuAverageUtilization: 70
    memoryAverageUtilization: 80

  service:
    type: ClusterIP
